name: pgweb-kemelzaidan
base: core18
version: git
summary: Cross-platform client for PostgreSQL databases
description: |
  Pgweb is a cross-platform web-based database browser for PostgreSQL,
  written in Go.

grade: devel
confinement: devmode

parts:
  pgweb:
    source-type: git
    source: https://github.com/sosedoff/pgweb.git
    plugin: go
    go-importpath: github.com/sosedoff/pgweb
    build-packages:
      - gcc

apps:
  pgweb:
    command: pgweb
